version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network
    environment:
      - PYTHONPATH=/app/src

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: